### ISSUE TITLE
Java class generation fails on default value objects

### ISSUE THREAD

**Issue by a-sayyed** [deweyjose/graphqlcodegen#103]
hello @deweyjose and thanks for the awesome maven plugin!

We recently noticed a problem with Java class generation when our schema has something like
```graphql
input SomeKindOfInput {
  nestedInput: NestedInput = {enumField : ENUM_VALUE1}
}

input NestedInput {
  enumField: SomeKindOfEnum!
}
```
where we attempt to give a field a default value of an object that has some field value.
The generated class is not a valid java class
```java
public class SomeKindOfInput {
  private NestedInput nestedInput = ObjectValue{objectFields=[ObjectField{name='enumField', value=EnumValue{name='ENUM_VALUE1'}}]};
} 
```

**Comment by deweyjose** [comment]
Hi @a-sayyed - sorry for the delay.

I think this is a bug in the core DGS codegen library. I've created an [issue](https://github.com/Netflix/dgs-codegen/issues/636) in their repo.

**Comment by deweyjose** [comment]
Closing this for now. Lets revisit if DGS fixes.
