### ISSUE TITLE
Consider allowing to configure class name prefixes for better usage alongside mapping frameworks

### ISSUE THREAD

**Issue by appreciated** [deweyjose/graphqlcodegen#113]
Our project is currently hindered using this plugin due to the following issue: backend model classes share identical names, leading to naming conflicts and the need to rely on package names for differentiation of the Classes.

To circumvent this issue, we've adopted a strategy of prefixing all model classes with "View". Since this seems currently not possible, I propose the addition of a feature that allows adding prefixes to the classes, such as "View", during the code generation phase. 

I appreciate your consideration of this feature request and am hopeful for its inclusion in a future update of the graphqlcodegen plugin.

**Comment by deweyjose** [comment]
Hi @appreciated - This project is a thin wrapper over the core Netflix DGS codegen library. 

Netflix uses Gradle thus no support for the maven community, and we built this maven port.

There are already open feature requests in the DGS framework repo. https://github.com/Netflix/dgs-codegen/issues/323

Can you engage with these to get it back on their radar. This is where the change/fix will need to be made.
