### ISSUE TITLE
Allow user to add custom directive to generated types

### ISSUE THREAD

**Issue by yamalameyooooo** [deweyjose/graphqlcodegen#114]
in type mapping allow users to add @sharable directive to PageInfo type 
Use case i am using codegen to generate connection, node, edge,cursor, pageinfo type during runtime
My concern is when integrating with a federated supergraph, same types gives compose error as PageInfo is same across all subgraphs.
To tackle this we need to add @sharable on the connection related types and that should reflect on the SDL of the running graphql project
Is there any way to add @sharable tags for all connection types like connection,edge,cursor, node, pageinfo
also can we add totalCount as a property in Connection Type so that it looks like :

```
Connection{
  edges:[Edge!]
  pageInfo:PageInfo!
  totalCount:Int!
}
```

At the end PageInfo should look like in SDL:
```
type PageInfo @cacheControl(maxAge: 30) @shareable @tag(name: "public"){
    hasPreviousPage: Boolean!
    hasNextPage: Boolean!
    startCursor: String
    endCursor: String
}
```

Ultimately there should be a way to pass `@cacheControl(maxAge: 30) @shareable @tag(name: "public")` to PageInfo Type in codegen in typemapping or in any other way

**Comment by yamalameyooooo** [comment]
@deweyjose can we have something like this?

**Comment by deweyjose** [comment]
hi @yamalameyooooo 

Just want to make sure I understand the ask. You'd like the ability to pass the values of directive arguments to the generated code? You'd want these as members on the classes themselves? Statics perhaps?

**Comment by deweyjose** [comment]
For @CacheControl can you share a bit more on the use-case? From my understanding the [federation-jvm](https://github.com/apollographql/federation-jvm) library will pass along the CacheControl information to Apollo Server (not sure about Router). More on that [here](https://github.com/apollographql/federation-jvm/pull/133)

**Comment by deweyjose** [comment]
Not sure I follow the @sharable question. You can add @sharable to all your connection related types in your subgraphs schema.

**Comment by deweyjose** [comment]
Today there is no way to get the SDL directive information into the generated code. The core dgs codegen library would need to be modified.

It's a little duplicative but you could take a look at [custom annotations](https://netflix.github.io/dgs/generating-code-from-schema/#generating-classes-with-custom-annotations) supported by DGS today.

**Comment by yamalameyooooo** [comment]
So here is my code, 
Schema file: 
```
type Query{
   product_experience_products_list( first: Int! = 10
        after: String
        last: Int
        before: String): ProductConnection!
}

type Product @connection @key(fields: "name") @cacheControl(maxAge: 600) @shareable{
    name: String!
}
```

Pom codegen config:
```
<configuration>
	<subPackageNameDatafetchers>graph.query</subPackageNameDatafetchers>
	<subPackageNameTypes>graph.schema</subPackageNameTypes>
	<schemaPaths>
		<param>src/main/resources/graphql/labapp.graphqls</param>
	</schemaPaths>
	<typeMapping>
		<ProductConnection>graphql.relay.SimpleListConnection&lt;Product&gt</ProductConnection>
	</typeMapping>
	<packageName>com.test.pagination</packageName>
	<outputDir>${project.build.directory}</outputDir>
</configuration>
```

This code works fine and the results into a runnable project where codegen generates the Relay Pagination Types as shown in the image
<img width="260" alt="Screenshot 2024-01-04 at 11 10 13 AM" src="https://github.com/deweyjose/graphqlcodegen/assets/52189801/3839f4f4-99c2-4ab3-95b3-2b9603c49ca2">
<img width="207" alt="Screenshot 2024-01-04 at 11 10 21 AM" src="https://github.com/deweyjose/graphqlcodegen/assets/52189801/cd05d6cc-f486-442e-86fa-4e847e9927be">
<img width="211" alt="Screenshot 2024-01-04 at 11 10 32 AM" src="https://github.com/deweyjose/graphqlcodegen/assets/52189801/e3a0b235-a614-4ffc-a091-74e19b916a14">
<img width="190" alt="Screenshot 2024-01-04 at 11 10 38 AM" src="https://github.com/deweyjose/graphqlcodegen/assets/52189801/c8c4be74-d079-4d8c-a3ee-bebd16d62a16">
<img width="156" alt="Screenshot 2024-01-04 at 11 10 43 AM" src="https://github.com/deweyjose/graphqlcodegen/assets/52189801/8409f5fe-8625-4c9e-94c9-80c62ed44b0d">

Now the concern is if i check the SDL for Type PageInfo as shown below:
<img width="1510" alt="Screenshot 2024-01-04 at 11 13 17 AM" src="https://github.com/deweyjose/graphqlcodegen/assets/52189801/55be1952-f3a6-4e78-be2d-853dc835ebce">
In this SDL i need to add @sharable directive as i have added in the schema file for type Product.
But these types like PageInfo, ProductEdge, are being generated by codegen in runtime so i am unable to add any directive to them specially in PageInfo.

@deweyjose

**Comment by yamalameyooooo** [comment]
I just want that when the project runs where codegen is generating these Relay Pagination types in the SDL, 
I want to add directives to them so that they should be like:
<img width="707" alt="Screenshot 2024-01-04 at 11 21 21 AM" src="https://github.com/deweyjose/graphqlcodegen/assets/52189801/f31dfb85-9a19-4a25-843b-820898d238c0">

**Comment by yamalameyooooo** [comment]
As you can see i am never defining Type PageInfo or Type ProductEdge in my code but those are being generated at runtime, even these are getting added to schema definition file, so i just want to pass on some directives like @sharable to the schema definition as above image.
So is there any way where i can pass on this information in the pom.xml configuration maybe in the typemapping section?

**Comment by deweyjose** [comment]
@yamalameyooooo - I see what you were asking now. Are you including a library that might have additional schema included with it? Can you share more of your pom file and a screen shot of the target folder where the code is being generated?

**Comment by deweyjose** [comment]
@yamalameyooooo one of my colleagues had a couple ideas
- explore dynamic schemas, you can modify existing static schemas at runtime https://netflix.github.io/dgs/advanced/dynamic-schemas/
- don't use @connection and define your own relay types with the federated directives.

**Comment by deweyjose** [comment]
@yamalameyooooo also, DGS warns about this use case in the docs about dgs-pagination

```The @connection directive only works for DGSs that are not required to register the static schema file with an external service (since the relay types are dynamically generated). For example, in a federated architecture involving a gateway, some gateway implementations may or may not recognize the @connection directive when working with a static schema file.
```

**Comment by yamalameyooooo** [comment]
Ahhh, I see, so the most convenient way will be to use dynamic schema maybe will give it a try
I wish Netflix soon supports federated directives on types which were added dynamically in the runtime by @connection

**Comment by deweyjose** [comment]
@yamalameyooooo I tried to get it working dynamic schema by implementing my own @DgsTypeDefinitionRegistry. It does not look possible to augment the connection related types that DGS will create automatically. They have their own @DgsTypeDefinitionRegistry bean, there is no way to intercept that one and augment the things it creates. You can change any of the static schema though.


I was brainstorming with someone recently on this issue - there may be a nice extension to the dgs-pagination we could recommend or even submit a PR for.

Something like this where we add directives to the type and specify which ones to propagate to the generated connection types.

`
type foo @connection(shareable, xyz) @shareable @xyz(bar="foo") {
}
`

Or maybe the rule is to just propagate them all:

`
type foo @connection @shareable @xyz(bar="foo") {
}
`

Or maybe we use spring configuration and specify directives to be applied to connection types.

Any thoughts?

**Comment by yamalameyooooo** [comment]
@deweyjose i was thinking the same thing about we add directives to the the codegen configuration and propagate to the generated connection types.

something like this maybe:
POM.xml

```
<configuration>
	<typeMapping>
		<ProductConnection>
			<directives>
				@cacheControl(maxAge: 30) @shareable @tag(name: "public")
			</directives>
			<type>
				graphql.relay.SimpleListConnection&lt;Product&gt
			</type>
		</ProductConnection>
	</typeMapping>
</configuration>
```

So that all the generated types related to relay pagination like ProductConnection,ProductConnectionEdge,PageInfo can have the user provided directives specially the ones for federation.

**Comment by yamalameyooooo** [comment]
If we can have this then we can use @connection types in federation and we don't have to worry about the types or its logic, the java based subgraph development and its implementation will be much friendly as right now i had made a subgraph using dgs and implemented the complete relay pagination by myself which makes the code very very ugly when we can just have this in the configuration and let the dgs handle that, 

But yes i would love to contribute to the PR if we get to know how we can do that

**Comment by yamalameyooooo** [comment]
@deweyjose maybe here https://github.com/Netflix/dgs-framework/blob/master/graphql-dgs-pagination/src/main/kotlin/com/netflix/graphql/dgs/pagination/DgsPaginationTypeDefinitionRegistry.kt

**Comment by deweyjose** [comment]
Hi @yamalameyooooo,
Couple of things to keep in mind. 

The plugin managed here converts static schema into Java or Kotlin code files. It does not interact with DGS initialization or dynamic schema generation at runtime. 

DgsPaginationTypeDefinitionRegistry class provides a @DgsTypeDefinitionRegistry Bean that does inject dynamic schema at runtime within our applications during DGS schema initialization. As I pointed out earlier, there is no way to add any additional directives to the @connection related types that DGS creates as dynamic schema at runtime. (at least I couldn't find a way).

The settings we provide in the pom for this plugin's configuration have no effect on DGS runtime. I think either schema or spring configuration is the way to communicate instructions to the DGS runtime code like DgsPaginationTypeDefinitionRegistry.  

Does this help clarify things a bit?

This will mean changes to `graphql-dgs-pagination` though. I'm happy to make a proposal on that one.

**Comment by deweyjose** [comment]
@yamalameyooooo - there is also another option depending on how do composition. My company has a step in our build pipeline the performs custom schema lints as well as a post processing step that injects various things into subgraph schema just before we send it to Apollo for composition. You could do something similar, just add @sharable and any other directive to the subgraph schema for composition.

**Comment by yamalameyooooo** [comment]
@deweyjose thats a great option to do now till netflix-dgs can give any permanent solution, as we also do have the Apollo, 
Can you help me in setting up how to inject the custom directive (federation based like @sharable and other ones) into the subgraph during build phase?
👀🥺

**Comment by yamalameyooooo** [comment]
@deweyjose are you changing the schema definition file after maven build? i was trying the same but the schema file inside the .jar doesnt not contain the PageInfo type which is auto generated by using @connection.
So i was wondering how you achieved in your pipeline to inject various directives and things into the subgraph schema and then send it to apollo for schema checks.
Require some of your guidance

**Comment by yamalameyooooo** [comment]
@deweyjose we are doing a rover subgraph publish by 
`$ rover subgraph publish $APOLLO_GRAPH_ID@$APOLLO_GRAPH_VARIANT --name $APOLLO_SUBGRAPH_NAME --schema $SCHEMA_PATH`
in the pipeline, this schema path has the schema with @connection tags but no PageInfo gets generated by the codegen in the schema file but its visible in the SDL service, how further can we intercept it and send it to apollo for composition, 
I have already written a script which will check the schema file for occurrence like ''type PageInfo' and will add the directives to it, but so far with codegen i am unable to fetch the running schema which has PageInfo type defined in it

JS script : 
```
const fs = require('fs');
const path = require('path');

const schemaPath = '/src/main/resources/graphql/schema.graphqls';

// Read the schema file
const schema = fs.readFileSync(schemaPath, 'utf8');

// Define the directive to be added
const sharableDirective = '@cacheControl(maxAge: 30) @shareable @tag(name: "public")';

// Find the location of the PageInfo type in the schema
const pageInfoIndex = schema.indexOf('type PageInfo');

// Check if the PageInfo type is found in the schema
if (pageInfoIndex !== -1) {
  // Find the position just after 'type PageInfo'
    const insertPosition = schema.indexOf('{', pageInfoIndex);

    // Insert the @sharable directive at the found position
    const updatedSchema = `${schema.slice(0, insertPosition)}${sharableDirective}${schema.slice(insertPosition)}`;

    // Write the updated schema back to the file
    fs.writeFileSync(schemaPath, updatedSchema, 'utf8');

    console.log('Added @sharable directive after PageInfo type and before curly brace.');
} else {
  console.error('PageInfo type not found in the schema.');
}
```

**Comment by deweyjose** [comment]
Hi @yamalameyooooo,

First you'll need your service running somewhere to extract the full schema... perhaps you can spin it up during pipeline execution temporarily? Perhaps it's a build time task that updates the checked in schema?

- execute the following to extract the running schema, it will have all the types that `graphql-dgs-pagination` injects. 

```graphql
query sdl {
  __service {
    sdl
  }
}
```

- add any additional directives to PageInfo and Connection related types you need
- replace the static schema file with the new one
- compose

Hope this helps.

**Comment by yamalameyooooo** [comment]
@deweyjose thankyou for the push, i created a script which reads the static schema and injects the directives and types related to relay pagination into a new schema file, which i am sending for apollo schema checks and publish, 
the change and development is in the process but i can see the light now

**Comment by deweyjose** [comment]
@yamalameyooooo I'm going to close out this issue. I'll follow up on the approach discussed with DGS in their repo. Best of luck!
