### ISSUE TITLE
The Parameter "generateInterfaceSetters" does not seem to work

### ISSUE THREAD

**Issue by appreciated** [deweyjose/graphqlcodegen#128]
### Description
I have encountered an issue where the `generateInterfaceSetters` parameter ( `<generateInterfaceSetters>true</generateInterfaceSetters>`) does not seem to be working as intended. Despite setting this parameter in my configuration, the expected interface setters are not being generated in the output.

### Expected Behaviour
When the `generateInterfaceSetters` parameter is set to `true`, I expect the generated code to include setter methods in the interfaces.

### Actual Behaviour
The generated code does not include the expected setter methods in interfaces, despite the `generateInterfaceSetters` parameter being set to `true`.

**Comment by deweyjose** [comment]
Hi @appreciated - I'll take a look at this issue tonight.

**Comment by deweyjose** [comment]
@appreciated That's the wrong parameter name. Can you try `<generateInterfaceMethodsForInterfaceFields>` instead? I'll update the doc header to match.

**Comment by deweyjose** [comment]
Hi @appreciated can you try again with version [1.60.1](https://github.com/deweyjose/graphqlcodegen/releases/tag/graphqlcodegen-maven-plugin-1.60.1)?

I am seeing setters on interfaces:

```
@JsonSubTypes(@JsonSubTypes.Type(value = Comment.class, name = "Comment"))
public interface Blarg {
  String getText();

  void setText(String text);
}
```

for schema

```
interface Blarg {
  text: String!
}

type Comment implements Blarg {
  id: ID!
  text: String!
}
```

**Comment by deweyjose** [comment]
@appreciated - going to close this for now as I don't believe this is an issue with the current version of the plugin. Please feel free to open a new issue if it is still not working for you.
