### ISSUE TITLE
Option `schemaJarFilesFromDependencies` don't work 

### ISSUE THREAD

**Issue by zorglube** [deweyjose/graphqlcodegen#136]

**Comment by deweyjose** [comment]
Hi @zorglube,

Taking a look at this now. But I think I found two issues.

1. It looks like the core DGS Codegen [library](https://github.com/Netflix/dgs-codegen/blob/6c11193ef908087981ee13a30f5e782e40821e96/graphql-dgs-codegen-core/src/main/kotlin/com/netflix/graphql/dgs/codegen/CodeGen.kt#L121) requires the `.graphql*` files to exist under `META-INF` for some reason. 
1. still researching a potential issue with dependencies on a SNAPSHOT version of a sibling module.

**Comment by deweyjose** [comment]
@zorglube I did find a small bug in plugin, where if you didn't have any local schema files to compile and only used external schema files it would not compile them. You'll need to package your external .graphq(s) files under META-INF for now. It looks like DGS sometimes uses `src/main/resources/META-INF/schema`.

**Comment by deweyjose** [comment]
@zorglube I also updated the https://github.com/deweyjose/graphqlcodegen-example repo with working external schema configuration

**Comment by zorglube** [comment]
Thank a lot for your reactivity !
