### ISSUE TITLE
Missing option to specify custom scalars in generated kotlin2 clients

### ISSUE THREAD

**Issue by errfld** [deweyjose/graphqlcodegen#152]
I bumped into an issue when generating clients and types using the new kotlin2 generator. There was no way to add a `coercing map` as one can do with java clients. I bit of investigation showed, this is already knows and addressed:

When generating [kotlin2 clients](https://netflix.github.io/dgs/advanced/kotlin-codegen/#usage) there is no options to specify any custom scalar types as is with the kotlin/java client. This has been addressed in [this issue](https://github.com/Netflix/dgs-framework/issues/1860) and was merged in [dgs-codegen 6.1.7](https://github.com/Netflix/dgs-codegen/releases/tag/v6.1.7). 

I created a [PR](https://github.com/deweyjose/graphqlcodegen/pull/151) to bump to 6.2.1 as this is the current stable release. 

Thanks for the work on this project, it allows me using DGS while being required to use maven 🙇‍♂️

**Comment by deweyjose** [comment]
Hanks for the PR @errfld - will do my best to get it released this weekend.

**Comment by deweyjose** [comment]
This #151 was merged/released today.
