### ISSUE TITLE
`addGeneratedAnnotation` should not be configured in usage section of README

### ISSUE THREAD

**Issue by erichaagdev** [deweyjose/graphqlcodegen#161]
When `addGeneratedAnnotation` is set to `true`, a timestamp is introduced in the generated sources. This makes it impossible to reproduce built artifacts byte-for-byte.

Below are two invocations of the https://github.com/deweyjose/graphqlcodegen-example project, with no changes being made between build invocations. Despite this, the built artifacts are different.

![image](https://github.com/deweyjose/graphqlcodegen/assets/5797900/bf9a0c2e-6d04-44d0-8e5d-7d615a5bdd62)

Fortunately, the default is `false`. However, the _Usage_ section of this project's README has it configured to `true`. Users are likely to copy-and-paste this without understanding the consequences. That line of the documentation should be removed. 

Additionally, the default when creating a project on https://start.spring.io is `true`. It would be great to have that not be the case. I can create a separate issue for that at [spring-io/start.spring.io](https://github.com/spring-io/start.spring.io).

See also:
- https://reproducible-builds.org/docs/definition/
- https://reproducible-builds.org/docs/timestamps/

**Comment by deweyjose** [comment]
Hi @erichaagdev 

Thanks for the issue. However I don't necessarily agree with you that `@Generated` should be the non default case. In my experience having @Generated enabled solves more problems than creates. What is your rational behind this opinion?

**Comment by deweyjose** [comment]
Hi @erichaagdev,

Please feel free to open an issue in Netflix DGS [codegen](https://github.com/Netflix/dgs-codegen) regarding the ability to suppress or configure the `optional` date element of the Generated annotation. This behavior is not controlled by this plugin.

**Comment by deweyjose** [comment]
I don't feel strongly about the usage comment so I removed it for now since there really are no other opinions in usage about overriding defaults.

**Comment by erichaagdev** [comment]
Thanks. I did create a PR here. https://github.com/spring-io/start.spring.io/pull/1533

And I see it's removed from the _Usage_ section now. Thanks!

**Comment by deweyjose** [comment]
@erichaagdev Interesting but `@Generated` is really useful for other tooling. Another way to solve for reproducible builds is to not generate code that has the optional date element set.

**Comment by erichaagdev** [comment]
Yes, I should have been more specific. The `@Generated` annotation itself is not a problem, it's the inconsistent output as a result of setting the `date` field. Another option is to not include the `date` field.

**Comment by deweyjose** [comment]
@erichaagdev - I think you'll pulling on an interesting thread. Ultimately Netflix DGS codegen folks control the `@Generated` annotation. I'll create an issue there and reference this one. If the date was removed we wouldn't need spring to change and setting addGeneratedAnnotation true doesn't impact reproducible builds.

**Comment by deweyjose** [comment]
https://github.com/Netflix/dgs-codegen/issues/702

**Comment by erichaagdev** [comment]
That would be a good change. Assuming the default value is `false` then having only `addGeneratedAnnotation` as `true` would still yield reproducible sources. I can leave a comment on my Spring PR that this option is being considered.
