### ISSUE TITLE
Default `schemaPaths` does not work as expected

### ISSUE THREAD

**Issue by Steve0x43** [deweyjose/graphqlcodegen#168]
The README states:

> If no `schemaPath` is specified, it will look in the src/main/resources/schema folder for any files with .graphqls extension.

and...

> ## schemaPaths
> - Required: false
> - Default: `${project.build.resources}/schema`

However, when not configuring `schemaPaths`, no schema files are found, even though one exists at `src/main/resources/schema/schema.graphqls`:

```
[INFO] --- graphqlcodegen:1.61.1:generate (dgs-codegen) @ graphql ---
[INFO] expanded schema paths: []
[INFO] changed schema files: []
[INFO] no files to generate
```

Relevant part of the `pom.xml`:

```xml
<build>
  <plugins>
    <plugin>
      <groupId>io.github.deweyjose</groupId>
      <artifactId>graphqlcodegen-maven-plugin</artifactId>
      <version>1.61.1</version>
      <executions>
        <execution>
          <id>dgs-codegen</id>
          <goals>
            <goal>generate</goal>
          </goals>
          <configuration>
            <packageName>com.demo.graphql</packageName>
            <!--<schemaPaths>
 	      <param>NOT CONFIGURED</param>
            </schemaPaths>-->
          </configuration>
        </execution>
      </executions>
    </plugin>
  </plugins>
</build>
```

**Comment by deweyjose** [comment]
@Steve0x43 - will take a look today.

**Comment by deweyjose** [comment]
This is fixed in release 1.61.4

**Comment by deweyjose** [comment]
@Steve0x43 can you try 1.61.4 and close this out when you verify. The fix worked for me during testing.

**Comment by deweyjose** [comment]
Sorry about that, updated to basedir. Can you check 1.61.5?
