### ISSUE TITLE
Update to dgs-codgen version 6.2.4

### ISSUE THREAD

**Issue by ChristopherGustafson** [deweyjose/graphqlcodegen#169]
A [new version was released](https://github.com/Netflix/dgs-codegen/releases) yesterday with quite a lot of updates.

**Comment by deweyjose** [comment]
@ChristopherGustafson I will take a look at the changes tonight. As long as there are no new options I may be able to publish tonight.

**Comment by ChristopherGustafson** [comment]
Great, did everything look ok?

**Comment by deweyjose** [comment]
My plan is to get this plugin up to DGS codegen 6.2.4 today. I want to understand the new functionality in 6.3 related to typemappings better before integrating it.

**Comment by deweyjose** [comment]
@ChristopherGustafson publishing a new build now. Going to close this issue.
