### ISSUE TITLE
Use of DGS extended scalars as types generates incorrect code

### ISSUE THREAD

**Issue by JeffBNimble** [deweyjose/graphqlcodegen#177]
We are using the DGS extended scalars, specifically the LocaleScalar type.

In our graphql schema, we declare the scalar as follows:

```
scalar Locale
```

And, we then specify Locale as the data type of one of our types, as follows:
```
type Team @cacheControl(maxAge: 60, scope: PUBLIC){
    id: ID!
    hl: Locale!
}
```

When we run our maven build using this codegen plugin, we get the following generated (summarized):

```java
import graphql.scalars.locale.LocaleScalar;

public class Team {
  private String id;

  private LocaleScalar hl;

public Team() {
  }

  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public LocaleScalar getHl() {
    return hl;
  }

  public void setHl(LocaleScalar hl) {
    this.hl = hl;
  }
}
```

At issue is that there is no way programmatically for us to create a LocaleScalar. So, we cannot invoke setHl with a LocaleScalar.

Note that we have this class which registers the scalar and maps the DGS extended scalar to a java.util.Locale.

```java
@DgsComponent
@DgsScalar(name = "Locale")
public class LocaleScalarRegistration implements Coercing<Locale, String> {
  @DgsRuntimeWiring
  public RuntimeWiring.Builder addLocaleScalarWiring(RuntimeWiring.Builder builder) {
    return builder.scalar(ExtendedScalars.Locale);
  }
}
```

I think what needs to instead be generated in this case is the following:

```java
import java.util.Locale;

public class Team {
  private String id;

  private Locale hl;

public Team() {
  }

  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public Locale getHl() {
    return hl;
  }

  public void setHl(Locale hl) {
    this.hl = hl;
  }
}
```

If I change the code manually after it has been generated, then DGS properly handles coercing the Locale to a string and vice-versa. When I post to our graphql endpoint with a locale string as an argument, DGS properly handles coercing the string to a locale.

**Comment by JeffBNimble** [comment]
If you agree that this is an error, I'm happy to try to submit a PR if you don't have time to fix quickly and you can advise me. I'm not all that familiar with the inner workings of this plugin.

**Comment by deweyjose** [comment]
Can you take a look at the <typeMapping> option.

I think what you want is to map LocaleScalar => Locale.


<typeMapping>
  <LocaleScalar>Locale</Localeascalar>
</typeMapping/>

**Comment by JeffBNimble** [comment]
Where do I put that declaration? I'm not familiar with that.

**Comment by deweyjose** [comment]
Hi @JeffBNimble 

I think you'll need to configure the `<typeMapping>` option.

If I add this to my example schema I'll get compile errors as the generated code doesn't include an import for anything other the basic scalar types (String, Integer etc). More here in the [DGS](https://netflix.github.io/dgs/generating-code-from-schema/#mapping-existing-types) docs.

```
scalar Locale

type Chair {
  id: ID!
  name: String!
  description: Locale!
}
```

When I add the following it tells the codegen tool how to map the GraphQL scalar to a Java type and my generated Chair class compiles correctly. 

```
 <typeMapping>
  <Locale>java.util.Locale</Locale>
</typeMapping>
```

**Comment by deweyjose** [comment]
The typeMapping and all other options supported by the plugin are in the [documentation](https://github.com/deweyjose/graphqlcodegen?tab=readme-ov-file#options).

**Comment by JeffBNimble** [comment]
Great! Thank you so much for your help.

**Comment by deweyjose** [comment]
No problem, let me know if that fixes it for you. Just put the typeMapping option in the <configuration> block.

**Comment by JeffBNimble** [comment]
That fixed it. Thank you again.
