### ISSUE TITLE
schemaPaths multiple files

### ISSUE THREAD

**Issue by wnederhof** [deweyjose/graphqlcodegen#18]
For larger GraphQL projects, it may happen that multiple schema files are required. In that case, for each and every GraphQL schema file, you'll have to add it to the pom. Is it possible to add support for adding paths? E.g.:
```
                    <schemaPaths>
                        <param>src/main/resources/schema/*.graphqls</param>
                    </schemaPaths>
```

**Comment by deweyjose** [comment]
I think this is already supported.

```
<configuration>
    <schemaPaths>
        <path>src/main/resources/schema</path>
    </schemaPaths>
</configuration>
```
