### ISSUE TITLE
Projection classes generate invalid constructors

### ISSUE THREAD

**Issue by ReyhanPatria** [deweyjose/graphqlcodegen#19]
The projection classes in my project generated a class using an extra argument that the parent class does not need

```
public class Shows_FooProjection extends BaseSubProjectionNode<ShowsProjectionRoot, ShowsProjectionRoot> {
  public Shows_FooProjection(ShowsProjectionRoot parent, ShowsProjectionRoot root) {
    super(parent, root, java.util.Optional.of("Foo"));
  }
}
```

This is from the example repository, the optional foo is marked as an error.

**Comment by deweyjose** [comment]
can you pull the latest from the example repo and try again. a number of changes have been made, I'm not seeing this issue now.

**Comment by ReyhanPatria** [comment]
I'm still having trouble. The generated projection class generated this import 
`import com.netflix.graphql.dgs.client.codegen.GraphQLQuery;` it was unresolved, and I cannot import it. Is there something I'm doing wrong?

**Comment by deweyjose** [comment]
Hi @ReyhanPatria  - if you want to use the generated client could you'll need to add the following dependency to your project.

```
<dependency>
            <groupId>com.netflix.graphql.dgs.codegen</groupId>
            <artifactId>graphql-dgs-codegen-client-core</artifactId>
        </dependency>
```

I'll close this issue in a day or so if I don't hear back from you.

**Comment by ReyhanPatria** [comment]
I don't see this problem anymore, thanks!

**Comment by yashrajk17** [comment]
I am also facing the same issue, even after adding 

<dependency>
            <groupId>com.netflix.graphql.dgs.codegen</groupId>
            <artifactId>graphql-dgs-codegen-client-core</artifactId>
        </dependency>
