### ISSUE TITLE
Is there a way to distinguish explicit null values from missing values?

### ISSUE THREAD

**Issue by Yang-Jace-Liu** [deweyjose/graphqlcodegen#21]
Thanks for the project. I have a question about how to distinguish explicit null values from missing values.

Let's use [the schema in your example](https://github.com/deweyjose/graphqlcodegen-example/blob/main/src/main/resources/schema/schema.graphqls). Suppose I have a mutation that accepts a `Show` object, which has `title` as `null` and there's no `releaseYear` passed in. When the object gets mapped to a JAVA POJO, both `title` and `releaseYear` are `null`. Is there any way that my application could be aware of the difference?

**Comment by deweyjose** [comment]
To the best of my knowledge there isn't a way.

Also - you need to create an input type for your mutation. You can't pass a non input type to a mutation.

I would think about making the input type require a releaseYear in this case.

How would your resolver handle the two scenarios: 1. "not present" null vs 2. "explicit" null, differently?

I've added a mutation to the example repo. 
```
type Query {
    shows(titleFilter: String): [Show]
}

type Mutation {
   createShow(showInput: ShowInput!): Show
}

type Show {
    id: Int
    title: String
    releaseYear: Int
}

input ShowInput {
    title: String!
    releaseYear: Int!
}
```

**Comment by Yang-Jace-Liu** [comment]
Thank you @deweyjose for your reply. I'm creating a mutation used for updating rows in the database. I'm trying to make the mutation have the ability to "partially update" and "nullify objects", so here's the question.

My design was: If the field is set to null explicitly, it means the request wants to nullify the field in the database. If the field is not presented, the field is ignored. If the field is set to a non-null value, we replace the old value with the new value passed in.

Since we cannot tell the difference between the first 2 scenarios after Inputs are mapped to Java classes, I guess I need to find another way around.

Thanks for your reply.
