### ISSUE TITLE
Maintainer

### ISSUE THREAD

**Issue by zorglube** [deweyjose/graphqlcodegen#27]
@deweyjose Is this possible for me to ask for me to be granted as maintainer (or the right status) to be able to produce new releases, through GitHub, in order to follow [dgs-codegen](https://github.com/Netflix/dgs-codegen) release rythm.

**Comment by deweyjose** [comment]
hi @zorglube appreciate the PRs. apologies for the release delays. In the future I'll definitely be a bit more responsive. 

Let me look into this. One the of the issues will be around securely distributing the plugin in maven central - this requires secure credentials and keys.

**Comment by zorglube** [comment]
Hey @deweyjose ,

Normally, in the project configuration, you can set-up some GitHub action -- like : publish release -- and you have a "secret" section that allows you to give some credentials to an action without show them to anyone.

**Comment by deweyjose** [comment]
Ok I'll look into it this weekend.

**Comment by deweyjose** [comment]
@zorglube did some work this weekend and added two new github action workflows: build and publish. 

The v1.16 release was managed by the the publish workflow - so much easier than what I was doing prior.

**Comment by zorglube** [comment]
I saw that, it seems very nice.

**Comment by zorglube** [comment]
Hey @deweyjose ! 

How it is going about the CI/CD  ?

**Comment by deweyjose** [comment]
Seems to be working just fine.
