### ISSUE TITLE
Central Repo

### ISSUE THREAD

**Issue by fabienmifsud** [deweyjose/graphqlcodegen#3]
Thank you to have written the maven plugin for the code generation, can you tell me how to use it since it is not available on maven central repo ?

**Comment by deweyjose** [comment]
Hi @fabienmifsud . Could you try release 1.7 It looks like the netflix core team released some of their libraries on maven central which means we don't have a dependency on jcenter any longer.

cc @sdoxsee

**Comment by mbunzel** [comment]
I'm not the OP but I gave the artifact on maven central a try and it works for me. The only remaining issue is that the readme still mentions the old group and artifact id on jcenter.

**Comment by deweyjose** [comment]
@mbunzel I'll clean that up today. Thanks for pointing that out.

**Comment by sdoxsee** [comment]
Haven't had a chance to check but if artifacts are on central now then my old repository PR can be pulled out again.

**Comment by deweyjose** [comment]
just pushed 1.8 with an updated readme, dropped jcenter from the pom

**Comment by deweyjose** [comment]
@fabienmifsud going to close this since @mbunzel verified were good as of 1.7
