### ISSUE TITLE
Add option to skip generation

### ISSUE THREAD

**Issue by seanf** [deweyjose/graphqlcodegen#31]
An option like `-Ddgs.codegen.skip` would be useful for build pipelines, to avoid repeating earlier work in later stages.

**Comment by zorglube** [comment]
Here it is [PR](https://github.com/deweyjose/graphqlcodegen/pull/33), know we're waiting for @deweyjose to merge it.

**Comment by deweyjose** [comment]
Hi @seanf I'd like to learn a little more about this use-case first. 

Why invoke the codegen plugin at all in this case? Have you taken a look at ways to achieve this with maven profiles - different plugins enabled for different profiles? 

Another option could be to use environment variables:

```
<plugin>
  <groupId>io.github.deweyjose</groupId>
  <artifactId>graphqlcodegen-maven-plugin</artifactId>
  <version>1.15</version>
  <executions>
    <execution>
      <goals>
        <goal>generate</goal>
      </goals>
      <phase>${env.DGSPHASE}</phase>
    </execution>
  </executions>
</plugin>
```

The plugin will run:
```
export DGSPHASE=generate-sources; mvn clean install
```

The plugin will not run:
```
export DGSPHASE=none; mvn clean install
```

**Comment by zorglube** [comment]
@deweyjose definitly the solution you purposed work to enable/disable codegen. However, I have a preference for the `-Ddgs.codegen.skip=true` option. 
That's my point of view.

**Comment by seanf** [comment]
@deweyjose Juggling Maven profiles can be a pain in the neck. Most popular Maven plugins seem to end up with a `skip` option eventually, probably because it's such a pain otherwise.

`skip` is just generally useful, but two cases have come up recently:

1. Configure the plugin at the top level of a multi-module project, but configure it to skip in all the modules except one. This allows invoking the plugin from the top level (and using the [short invocation](https://maven.apache.org/guides/introduction/introduction-to-plugin-prefix-mapping.html#specifying-a-plugins-prefix) which omits the `groupId`) without running it against modules where it makes no sense.
2. In a CI situation, I may need to run parts of the Maven lifecycle again in a different stage of the pipeline. If the code has already been generated, it's nice to have the option to skip unnecessary code generation easily. With this feature, adding `-Ddgs.codegen.skip` is a small change which doesn't affect the pom. Without a built-in skip feature, achieving the same thing with a Maven profile (activated by the absence of a command line property) will require changes to at least one pom, and several lines of XML. This could also be achieved with the environment variable you suggest, but I think `-Ddgs.codegen.skip` is more readable than `DGSPHASE=none`, especially if you need to skip multiple plugins.

**Comment by seanf** [comment]
Thanks @deweyjose and @zorglube!
