### ISSUE TITLE
Exclude generated files from code coverage report

### ISSUE THREAD

**Issue by bartebor** [deweyjose/graphqlcodegen#36]
Hello!
Generated code is currently included in code coverage reports which may be undesirable. It would be great to annotate generated classes with some custom `@Generated` annotation. Jacoco excludes such annotated files automatically. This feature could be configurable to suit different needs.

**Comment by bartebor** [comment]
You are right; I filed issue in dgs-codegen project: https://github.com/Netflix/dgs-codegen/issues/420

**Comment by deweyjose** [comment]
@bartebor thanks! As soon as they add support we'll integrate with the new version.

**Comment by yonatang** [comment]
hi @deweyjose , Netflix just merged my PR https://github.com/Netflix/dgs-codegen/pull/424 to support that feature. I'd appreciate if you can add that to the maven plugin. Or, if you'd prefer, I can submit a PR for that as well?

**Comment by anidzgor** [comment]
Hello @deweyjose, 6 days ago Netflix release version v5.2.5, it would be great if it will be updated in your project :)
[[v5.2.5](https://github.com/Netflix/dgs-codegen/releases/tag/v5.2.5)]

**Comment by bartebor** [comment]
Hi @deweyjose, dgs folks followed up on the issue and added custom `@Generated` annotation in https://github.com/Netflix/dgs-codegen/releases/tag/v5.2.6 to make JaCoCo happy. Could you update your project accordingly? Thanks!
