### ISSUE TITLE
Include Class Imports and custom annoations

### ISSUE THREAD

**Issue by markwimpory** [deweyjose/graphqlcodegen#66]
I could not get this to work wit the maven plugin.  The class always remained as a string in the built annotation.  Enums worked fine.

Example with Class Object:

Since GraphQL parser does not have built-in support for class objects, a class is represented as a string ending with ".class" in the schema

type Person @annotate(name: "ValidPerson", type: "validator", inputs: {groups: "BasicValidation.class"}) {
    name: String @annotate(name: "com.test.anotherValidator.ValidName")
}

**Comment by deweyjose** [comment]
Hi @markwimpory not sure I follow. DGS codegen is schema first - it generates java/kotlin classes for graphql schema files in your project. It sounds like your looking for a code first approach?
