### ISSUE TITLE
Support for 6.0.1

### ISSUE THREAD

**Issue by noorul** [deweyjose/graphqlcodegen#68]
There is a new major release 6.0.0 and the latest version is 6.0.1. Is this supported?

**Comment by deweyjose** [comment]
Hi @noorul - the core DGS framework the DGS codegen library are two different libraries. This project only provides a thin wrapper around the codegen library for maven as Netflix uses Gradle internally.

The latest release for codegen is 5.6.9 which this project is current with. This plugin should still work, generate POJOs for your schema, with projects that are on DGS framework 6.x.

Hope this helps
