### ISSUE TITLE
GenerateClient not generating query builders

### ISSUE THREAD

**Issue by adjiandov** [deweyjose/graphqlcodegen#7]
When ```<generateClient>true</generateClient>``` is added to the configuration it does not generate the client API classes.
Plugin definition:
```<plugin>
                <groupId>io.github.deweyjose</groupId>
                <artifactId>graphqlcodegen-maven-plugin</artifactId>
                <version>1.8</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <generateClient>true</generateClient>
                    <schemaPaths>
                        <param>src/main/resources/schema/schema.graphqls</param>
                    </schemaPaths>
                    <packageName>${project.base}/generated</packageName>
                </configuration>
            </plugin>
```

**Comment by deweyjose** [comment]
Hi @adjiandov, I'll take a look today.

**Comment by adjiandov** [comment]
Hi @deweyjose did you had a chance to look at it? Meanwhile I have tried the gradle plugin and with a gradle build it works.

Thank you

**Comment by SydoxX** [comment]
Problem seems to persist, I'm only able to generate `types`.

**Comment by deweyjose** [comment]
Hi @adjiandov  @SydoxX ,

Can you share your schema, or a snippet of it? I'm able to generate the client query and project files in the graphqlcodegen-example repo.

**Comment by zorglube** [comment]
Hi guys ! 
I have the same issue.

**Comment by zorglube** [comment]
> > Hi guys !
> > I have the same issue.
> 
> Could you share your schema file or a snippet of it?

I can't but I'll make few try with public schema.

**Comment by zorglube** [comment]
My bad, it work, it was just a bad conf I did.

**Comment by deweyjose** [comment]
Can we close this then? I don't have any trouble either. If folks still having issues want to share an example schema I'm happy to take a closer look next week. Otherwise let's close this.

**Comment by zorglube** [comment]
My side, you can close. 

By the way, please have a look on my PR ;-)

**Comment by SydoxX** [comment]
I still have this problem. I will try to recreate it with a smaller schema tomorrow.

**Comment by zorglube** [comment]
> I still have this problem. I will try to recreate it with a smaller schema tomorrow.

Maybe it will help, here is are my setting : 

```
			<plugin>
				<groupId>io.github.deweyjose</groupId>
				<artifactId>graphqlcodegen-maven-plugin</artifactId>
				<executions>
					<execution>
						<id>generate graph schema DSL</id>
						<goals>
							<goal>generate</goal>
						</goals>
						<phase>generate-sources</phase>
					</execution>
				</executions>
				<configuration>
					<exampleOutputDir>${project.build.directory}/generated-examples</exampleOutputDir>
					<generateBoxedTypes>false</generateBoxedTypes>
					<generateClient>true</generateClient>
					<generateDataTypes>true</generateDataTypes>
					<generateInterfaces>false</generateInterfaces>
					<includeMutations></includeMutations>
					<includeQueries></includeQueries>
					<kotlinAllFieldsOptional>false</kotlinAllFieldsOptional>
					<language>java</language>
					<maxProjectionDepth>2</maxProjectionDepth>
					<omitNullInputFields>false</omitNullInputFields>
					<outputDir>${project.build.directory}/generated-sources</outputDir>
					<packageName>com.cacib.loanscape.rpx</packageName>
					<schemaPaths>
						<schemaPath>${schema.directory}/${schema.file}</schemaPath>
					</schemaPaths>
					<shortProjectionNames>false</shortProjectionNames>
					<skipEntityQueries>false</skipEntityQueries>
					<snakeCaseConstantNames>false</snakeCaseConstantNames>
					<subPackageNameClient>client</subPackageNameClient>
					<subPackageNameDatafetchers>datafetchers</subPackageNameDatafetchers>
					<subPackageNameTypes>types</subPackageNameTypes>
					<typeMapping></typeMapping>
				</configuration>
			</plugin>
```

**Comment by SydoxX** [comment]
Ok, found the problem. The schema generated by my GraphQL backend (Hasura) uses `type query_root` as the root query.
So my schema looks like this:
```graphql
schema {
  query: query_root
  Mutation: mutation_root
  Subscription: subscription_root
}
...
```
I guess that's still a valid GraphQL schema but the generator requires the query root to be named `Query`. Renaming the schemas `query_root` to `Query` will result in a generated client.

**Comment by SydoxX** [comment]
To recreate the problem:
this schema works: https://github.com/marmelab/GraphQL-example/blob/master/schema.graphql
this schema doesn't: https://gist.github.com/SydoxX/b666b7129092b0f896fdadc5c3fcb795
Only change is renaming `Query` to `query_root` and `Mutation` to `mutation_root`.

I guess this is a problem of the generator itself.
