### ISSUE TITLE
Provide a way to pass Java Generic Class as an argument to <typeMapping> 

### ISSUE THREAD

**Issue by navinyashende** [deweyjose/graphqlcodegen#70]
Current Behavior: Since the configuration is xml based it is not able to pass Generic types as an argument to the typeMapping.

Expected Behavior:  We should be able to pass generic type as an argument to typeMapping using the application properties.

**Comment by navinyashende** [comment]
I am trying to implement pagination using the steps provided here and need to pass generic type to codegen as described here https://netflix.github.io/dgs/advanced/relay-pagination/

**Comment by deweyjose** [comment]
Hi @navinyashende - did you try escaping the <> characters inside the TypeMapping element?

&ltT&gt for example?
