### ISSUE TITLE
What is the difference between graphql-dgs-codegen-core and graphql-dgs-codegen-client-core?

### ISSUE THREAD

**Issue by heilbad** [deweyjose/graphqlcodegen#76]
In the example project of this plugin the dependency 

```
<dependency>
     <groupId>com.netflix.graphql.dgs.codegen</groupId>
     <artifactId>graphql-dgs-codegen-client-core</artifactId>
</dependency>
```
 
is used. 
client-core is currently stuck at version 5.1.17 (from March last year).

On the dgs documentation https://netflix.github.io/dgs/generating-code-from-schema/ the dependency metioned is "codegen-core":
```
<dependency>
    <groupId>com.netflix.graphql.dgs.codegen</groupId>
    <artifactId>graphql-dgs-codegen-core</artifactId>
</dependency>
```
This one is also continuously getting new versions. 
Is it possible to use a recent version of "codegen-core" with this plugin?

**Comment by deweyjose** [comment]
Hi @heilbad - I'm going to make a pass through the example repo and build out a working example. The client module doesn't do anything and it should. As part of that I'll clean up the dependencies.

**Comment by deweyjose** [comment]
Hi @heilbad - I've updated the example repo with a working setup.

`graphql-dgs-codegen-core` is the core library for code generation.

`graphql-dgs-codegen-client-core` is another library that is required to as well if you generate the client types. 

`graphql-dgs-codegen-core` is updated often and we try to keep up.
