### ISSUE TITLE
Wildcard for specifying schema files 

### ISSUE THREAD

**Issue by CNAChino** [deweyjose/graphqlcodegen#88]
Using wildcard does not work.  The use case is .json files exist in `somefolder` and want to exlude them.

```
<schemaPaths>
    <param>somefolder/*.graphqls</param>
</schemaPaths>
```

**Comment by deweyjose** [comment]
Hi @CNAChino if you use the default `src/main/resources/schema` only the `.graphqls` files will be included, no need to specify anything.
