### ISSUE TITLE
Duplicate entries in schemaPaths

### ISSUE THREAD

**Issue by sherilbenjamin** [deweyjose/graphqlcodegen#91]
![image](https://github.com/deweyjose/graphqlcodegen/assets/59103017/f7c250ac-6c4b-4b49-a08f-f1a9a102c4e5)

Throws [ERROR] Failed to execute goal io.github.deweyjose:graphqlcodegen-maven-plugin:1.29:generate (default) on project ***: Execution default of goal io.github.deweyjose:graphqlcodegen-maven-plugin:1.29:generate failed: Duplicate entries in schemaPaths -> [Help 1]

**Comment by deweyjose** [comment]
Hi @sherilbenjamin 

Can you upgrade to 1.39 of the plugin and let me know if this is still a problem. I'm not seeing the same issue.
