### ISSUE TITLE
Generating of graphql client in Kotlin is generating classes with unresolved references

### ISSUE THREAD

**Issue by MinionCZ** [deweyjose/graphqlcodegen#92]
Hello,
I am having trouble with generating client from graphql schema in Kotlin. Generated classes have unresolved references such as  com.netflix.graphql.dgs.codegen.GraphQLProjection and function field in getters. Also when i try to generate v2 client api it does not generate anything.  I am using Kotlin 1.9.0 and plugin version 1.39. Here is my generated class:
```
package cz.cvut.fel.czm.temataprojectsclient.generated.client

import com.netflix.graphql.dgs.codegen.GraphQLProjection

public class DepartmentProjection : GraphQLProjection() {
  public val id: DepartmentProjection
    get() {
      field("id")
      return this
    }

  public val webCze: DepartmentProjection
    get() {
      field("webCze")
      return this
    }

  public val webEng: DepartmentProjection
    get() {
      field("webEng")
      return this
    }

  public val nameCze: DepartmentProjection
    get() {
      field("nameCze")
      return this
    }

  public val nameEng: DepartmentProjection
    get() {
      field("nameEng")
      return this
    }

  public val code: DepartmentProjection
    get() {
      field("code")
      return this
    }
}
```
And here is how i use plugin in pom.xml:
```
            <plugin>
                <groupId>io.github.deweyjose</groupId>
                <artifactId>graphqlcodegen-maven-plugin</artifactId>
                <version>${graphqlcodegen.maven.plugin.version}</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <schemaPaths>
                        <param>${project.basedir}/../temata-projects-service-logic/src/main/resources/schema</param>
                    </schemaPaths>
                    <packageName>cz.cvut.fel.czm.temataprojectsclient.generated</packageName>
                    <generateClientApi>true</generateClientApi>
                    <outputDir>${project.basedir}/src/main/kotlin</outputDir>
                    <subPackageNameDatafetchers>fetchers</subPackageNameDatafetchers>
                    <subPackageNameTypes>types</subPackageNameTypes>
                    <language>kotlin</language>
                    <generateKotlinClosureProjections>true</generateKotlinClosureProjections>
                </configuration>
            </plugin>
```
Thank you for time.

**Comment by deweyjose** [comment]
Hi @MinionCZ  - can you share you pom file? What version the following dependency do you have?

```
<dependency>
            <groupId>com.netflix.graphql.dgs.codegen</groupId>
            <artifactId>graphql-dgs-codegen-client-core</artifactId>
 </dependency>
```

**Comment by MinionCZ** [comment]
Thanks for your reply @deweyjose,
Here is my pom.xml
``
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>cz.cvut.fel.czm.temataprojectsservice</groupId>
        <artifactId>temata-projects-service</artifactId>
        <version>0.0.1-SNAPSHOT</version>
    </parent>

    <artifactId>temata-projects-service-client</artifactId>
    <version>${service.version}</version>
    <name>temata-projects-service-client</name>
    <description>temata-projects-service-client</description>

    <dependencies>
        
        <dependency>
            <groupId>com.netflix.graphql.dgs.codegen</groupId>
            <artifactId>graphql-dgs-codegen-core</artifactId>
            <version>${graphql.dgs.codegen.core.version}</version>
        </dependency>

        <dependency>
            <groupId>com.netflix.graphql.dgs.codegen</groupId>
            <artifactId>graphql-dgs-codegen-client-core</artifactId>
            <version>${graphql.dgs.codegen.client.core.version}</version>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter</artifactId>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-annotations</artifactId>
        </dependency>
        <dependency>
            <groupId>org.jetbrains.kotlin</groupId>
            <artifactId>kotlin-reflect</artifactId>
        </dependency>
        


    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>io.github.deweyjose</groupId>
                <artifactId>graphqlcodegen-maven-plugin</artifactId>
                <version>${graphqlcodegen.maven.plugin.version}</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <schemaPaths>
                        <param>${project.basedir}/../temata-projects-service-logic/src/main/resources/schema</param>
                    </schemaPaths>
                    <packageName>cz.cvut.fel.czm.temataprojectsclient.generated</packageName>
                    
                    <outputDir>src/main/kotlin</outputDir>
                    <subPackageNameDatafetchers>fetchers</subPackageNameDatafetchers>
                    <subPackageNameTypes>types</subPackageNameTypes>
                    <language>kotlin</language>
                    
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-clean-plugin</artifactId>
                <version>${maven.clean.plugin.version}</version>
                <configuration>
                    <filesets>
                        <fileset>
                            <directory>src/main/kotlin/cz/cvut/fel/czm/temataprojectsclient/generated</directory>
                            <includes>
                                <include>**</include>
                            </includes>
                            <followSymlinks>false</followSymlinks>
                        </fileset>
                    </filesets>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.jetbrains.kotlin</groupId>
                <artifactId>kotlin-maven-plugin</artifactId>
                <version>${kotlin.version}</version>
                <executions>
                    <execution>
                        <id>compile</id>
                        <phase>compile</phase>
                        <goals>
                            <goal>compile</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <args>
                        <arg>-Xjsr305=strict</arg>
                    </args>
                </configuration>
            </plugin>
        </plugins>
    </build>

</project>

I also have version 5.1.17 of graphql-dgs-codegen-client-core which is the latest at this point i think. If we resolve this issue i can help you prepare short demo for Kotlin.

**Comment by pavel-sedek** [comment]
Any news about this issue?

**Comment by deweyjose** [comment]
@pavel-sedek any chance you could take a second look using release v1.51.1?

**Comment by pavel-sedek** [comment]
@deweyjose I have noticed your reply to my colleague. We'll check it and let you know.

**Comment by deweyjose** [comment]
going to close this issue then
