### ISSUE TITLE
Do not generate sources if schema was not changed

### ISSUE THREAD

**Issue by MateuszStefek** [deweyjose/graphqlcodegen#93]
Currently, the plugin generates Java files, even if the schema was not changed, causing unnecessary compilations, when incremental compilation is used.
Can we get an option to allow incremental regeneration?

This could be something similar to `skipGenerationIfSchemaHasNotChanged` from `graphql-maven-plugin`:
https://graphql-maven-plugin-project.graphql-java-generator.com/graphql-maven-plugin/generateServerCode-mojo.html#skipgenerationifschemahasnotchanged

**Comment by deweyjose** [comment]
That's a really neat idea. How much build time would you expect to save on your builds?

**Comment by MateuszStefek** [comment]
It's about 1 minute per each `mvn compile` . There are other modules that depend on the module with graphql - these are also recompiled, because of a detected change in their dependencies. These unnecessary compilation times quickly add up when there's a bigger team.

**Comment by deweyjose** [comment]
Hi @MateuszStefek  - going to take a look this weekend. Apologies for the delay.

**Comment by MateuszStefek** [comment]
Great, thanks! I can confirm that the 1.50 version of the plugin helped with unnecessary recompilations.
