### ISSUE TITLE
The plugin conflicts with openapi-generator-maven-plugin

### ISSUE THREAD

**Issue by emeraldhieu** [deweyjose/graphqlcodegen#98]
Hi guys!

I have a project that reproduces the issue here https://github.com/emeraldhieu/issue-reproduction/tree/master/order

If you build it, the `OrderResponse` is not recognized in the classpath. If you comment out the `build-helper-maven-plugin`, the graph type `Order` is not recognized in the classpath. Please reimport the module whenever building the module.

Could you please help me fix it?

**Comment by deweyjose** [comment]
Can you share the maven output? I was able to build your project from the command line with no issues. Seems to startup up in IntelliJ just fine as well.

**Comment by deweyjose** [comment]
Hi @emeraldhieu  - is the repo in the current broken state? I cloned, built and it ran in IntelliJ without issue. 

I see your generated REST and GraphQL code files under generated-sources. I'v run into trouble in the past with this approach.

**Comment by emeraldhieu** [comment]
Yes, my repo is in a broken state because of using two code generators. It's served for reproducing the issue. I have compilation errors in IntelliJ. It's like the generated source config conflict each other.

**Comment by deweyjose** [comment]
The issue in IntelliJ is that it can't find the generated sources for openapi at the root of generated-sources. That plugin includes `src/java/main` in the generated structure - confusing IJ.

Here's my recommendation:

**Comment by deweyjose** [comment]
Let me know if that helps. I'm going to close this issue tomorrow as this is a maven configuration issue outside of the DGS codegen plugin.

**Comment by emeraldhieu** [comment]
@deweyjose It works perfectly!
